version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-image
    container_name: laravel-app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    expose:
      - 9000
    volumes:
      - .:/var/www/html
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
      
    networks:
      - laravel
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-psecret"]
      retries: 3
      timeout: 5s

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel
volumes:
  mysql-data:

networks:
  laravel:
    driver: bridge
